apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-ui-deployment
  namespace: final-project
  labels:
    app: chat-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-ui
  template:
    metadata:
      labels:
        app: chat-ui
    spec:
      containers:
      - name: chat-ui
        image: vakiti3010/chatbot-ui:2.0.9
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: chat-ui-service
  namespace: final-project
spec:
  selector:
    app: chat-ui
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP


